### ISSUE TITLE
Uncaught TypeError: $.browser is undefined

### ISSUE THREAD

**Issue by spartac** [vafour/vafpress-framework#129]
Hi
After WP5.5 update, the sub panels aren't opening , with lot of console js bugs.
```
Uncaught TypeError: this[binder] is not a function
    tipsy jQuery
    init_tipsy http://localhost/wordpress/wp-content/plugins/favpress/favpress-framework/public/js/shared.js?ver=1.1:1154
    <anonymous> http://localhost/wordpress/wp-content/plugins/favpress/favpress-framework/public/js/shared.js?ver=1.1:1159
```
The toggle of the sub panels arent working as well.
Do you plan for any update soon with the fixes?

**Comment by dkostelyanets** [comment]
Same on me. As i understand still no any solutions?

**Comment by DebugTheCode** [comment]
I'm also experiencing this error after updating WordPress to 5.8.x.
